server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file://Users/ryadav1/personal/foodiebook/foodie-config-properties
---

spring:
    profiles: cloud
    cloud:
      config:
        server:
          git:
            uri: https://github.com/rohityadav/foodie-config-properties
---

---

spring:
    profiles: docker
    cloud:
      config:
        server:
          git:
            uri: https://github.com/rohityadav/foodie-config-properties
---

